set(CMAKE_SYSROOT "C:/WohlMinGW32/")

set(CMAKE_SYSTEM_PREFIX_PATH "C:/WohlMinGW32/")

set(CMAKE_C_COMPILER "C:/WohlMinGW32/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "C:/WohlMinGW32/bin/g++.exe")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
